### ISSUE TITLE
Dashboard – Flow Runs – "Show all" button doesn't go away when showing all

### ISSUE THREAD

**Issue by brandonreid** [PrefectHQ/prefect-ui-library#1614]
On the dashboard Flow Runs card, when clicking the "Show more" button to view more runs for a flow, the button persists even when all flow runs have been retrieved. The expectation is that this button will stop showing once there are no more to show.

**Comment by MZalfred** [comment]
the issue with the "Show more" button on the dashboard Flow Runs card persists even after retrieving all flow runs. The expected behavior is that the button should disappear when there are no more flow runs to show. To address this, one should understand the code logic, inspect API responses, and check the front-end JavaScript code handling the button. Debugging and testing different scenarios, such as having no flow runs or a large number of runs, can help identify the problem. Once the issue is identified, propose and implement a fix, and ensure it is thoroughly tested and reviewed before deploying it to the production environment. Proper documentation of the investigation, resolution steps, and the fix will aid future troubleshooting. Communication with the team and stakeholders about the progress and resolution of the issue is also essential.
